<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>


    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.18" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.18" />
        <PackageReference Include="MudBlazor" Version="8.*"/>
        <PackageReference Include="Scalar.AspNetCore" Version="2.16.16" />
    </ItemGroup>


    <ItemGroup>
      <ProjectReference Include="..\VehicleTracking.Application\VehicleTracking.Application.csproj" />
      <ProjectReference Include="..\VehicleTracking.Persistence\VehicleTracking.Persistence.csproj" />
    </ItemGroup>


    <ItemGroup>
      <AdditionalFiles Include="Components\Pages\Login.razor" />
    </ItemGroup>
</Project>